version: '3'

services:

    app:
        build: .
        env_file: .env
        container_name: cms
        ports:
            - "8000:8000"
        volumes:
            - static-data:/static

volumes:
    static-data: