version: '3.8'

services:

    nginx:
        image: nginx:alpine
        container_name: cms-gateway
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app

    app:
        build: .
        env_file: .env
        container_name: cms
        ports:
            - "8000"
        volumes:
            - .:/app