version: '3.8'

services:

    app:
        build: .
        env_file: .env
        container_name: cms
        ports:
            - "8000"
        volumes:
            - static-data:/vol/static

    proxy:
        build:
            context: ./proxy
        env_file: .env
        volumes:
            - static-data:/vol/static
        ports:
            - 80:80
        depends_on:
            - app

volumes:
    static-data: